## 数据处理
1. 两张图片上下拼成一张图片
2. excel数据label改成npy文件

In [12]:
## 两张图片上下拼成一张图片
import os
from PIL import Image

def combine_images(top_image_path, bottom_image_path, output_image_path):
    # 打开顶部和底部图片
    top_image = Image.open(top_image_path)
    bottom_image = Image.open(bottom_image_path)

    # 获取顶部和底部图片的宽度和高度
    top_width, top_height = top_image.size
    bottom_width, bottom_height = bottom_image.size

    # 找到两张图片中的最大宽度
    max_width = max(top_width, bottom_width)

    # 调整两张图片的宽度到最大宽度
    top_image = top_image.resize((max_width, top_height), Image.Resampling.LANCZOS)
    bottom_image = bottom_image.resize((max_width, bottom_height), Image.Resampling.LANCZOS)

    # 创建一个新的图片对象，高度为两张图片高度之和，宽度为最大宽度
    new_image = Image.new('RGB', (max_width, top_height + bottom_height))

    # 将顶部和底部图片粘贴到新图片上
    new_image.paste(top_image, (0, 0))
    new_image.paste(bottom_image, (0, top_height))

    # 保存新图片
    new_image.save(output_image_path)
    print(f"图片已合并并保存为：{output_image_path}")


root_dir = "D:\Program\ThreeD\Project\TU" # 原始数据路径
output_dir1 = "D:\Program\ThreeD\Project\easy\\train_dataset" # 保存数据路径
output_dir2 = "D:\Program\ThreeD\Project\easy\\test_dataset" 
total_num = 38

for i in range(total_num):
    id1 = i*2 + 1
    id2 = i*2 + 2
    id3 = i+1
    file1_path = os.path.join(root_dir, f"{id1}.jpg")
    file2_path = os.path.join(root_dir, f"{id2}.jpg")
    ## 因为数据量太少，测试集一次，训练集重复三次
    file3_path = os.path.join(output_dir2, f"{id3}.jpg")
    combine_images(file1_path, file2_path, file3_path)
    file3_path = os.path.join(output_dir1, f"{id3}.jpg")
    combine_images(file1_path, file2_path, file3_path)
    id3 = id3 + total_num
    file3_path = os.path.join(output_dir1, f"{id3}.jpg")
    combine_images(file1_path, file2_path, file3_path)
    id3 = id3 + total_num
    file3_path = os.path.join(output_dir1, f"{id3}.jpg")
    combine_images(file1_path, file2_path, file3_path)

<>:33: SyntaxWarning: invalid escape sequence '\P'
<>:34: SyntaxWarning: invalid escape sequence '\P'
<>:35: SyntaxWarning: invalid escape sequence '\P'
<>:33: SyntaxWarning: invalid escape sequence '\P'
<>:34: SyntaxWarning: invalid escape sequence '\P'
<>:35: SyntaxWarning: invalid escape sequence '\P'
C:\Users\董子能\AppData\Local\Temp\ipykernel_3204\710290853.py:33: SyntaxWarning: invalid escape sequence '\P'
  root_dir = "D:\Program\ThreeD\Project\TU" # 原始数据路径
C:\Users\董子能\AppData\Local\Temp\ipykernel_3204\710290853.py:34: SyntaxWarning: invalid escape sequence '\P'
  output_dir1 = "D:\Program\ThreeD\Project\easy\\train_dataset" # 保存数据路径
C:\Users\董子能\AppData\Local\Temp\ipykernel_3204\710290853.py:35: SyntaxWarning: invalid escape sequence '\P'
  output_dir2 = "D:\Program\ThreeD\Project\easy\\test_dataset"


图片已合并并保存为：D:\Program\ThreeD\Project\easy\test_dataset\1.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\train_dataset\1.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\train_dataset\39.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\train_dataset\77.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\test_dataset\2.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\train_dataset\2.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\train_dataset\40.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\train_dataset\78.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\test_dataset\3.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\train_dataset\3.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\train_dataset\41.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\train_dataset\79.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\test_dataset\4.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\train_dataset\4.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\train_dataset\42.jpg
图片已合并并保存为：D:\Program\ThreeD\Project\easy\train_dataset\80.jpg
图片已合并并保存为：D:\Program

In [25]:
## 处理label
import numpy as np

total_num = 38
output_dir1 = "D:\Program\ThreeD\Project\easy\\train_dataset" # 保存数据路径
output_dir2 = "D:\Program\ThreeD\Project\easy\\test_dataset" 
label = [
    [2, 1, 2, 1], #
    [2, 1, 1, 1],
    [2, 1, 1, 2],
    [2, 1, 2, 2],
    [2, 3, 1, 2], 
    [2, 3, 1, 1], #
    [2, 3, 2, 1],
    [2, 3, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 1],
    [2, 2, 1, 1], #
    [2, 2, 1, 2],
    [2, 0, 1, 0],
    [2, 0, 2, 0],
    [3, 1, 2, 2],
    [4, 1, 2, 2], # 
    [4, 1, 1, 2],
    [4, 1, 1, 1],
    [3, 1, 1, 1],
    [3, 2, 1, 1],
    [4, 2, 1, 1], #
    [4, 2, 1, 2],
    [3, 2, 1, 2],
    [3, 3, 1, 2],
    [4, 3, 1, 2],
    [3, 1, 1, 2], #
    [3, 1, 2, 1],
    [3, 2, 2, 1],
    [3, 2, 2, 2],
    [3, 3, 2, 2],
    [3, 3, 2, 1], #
    [3, 3, 1, 1],
    [4, 1, 2, 1],
    [4, 2, 2, 1],
    [4, 2, 2, 2],
    [4, 3, 2, 2],
    [4, 3, 2, 1],
    [4, 3, 1, 1],
]

for i in range(total_num):
    np_array = np.array(label[i])
    np_array = np_array.reshape(-1, 1)
    print(np_array)
    id = i + 1
    # 保存到测试文件夹
    file3_path = os.path.join(output_dir2, f"{id}.npy")
    # print(file3_path)
    np.save(file3_path, np_array)
    # 保存到训练文件夹
    file3_path = os.path.join(output_dir1, f"{id}.npy")
    np.save(file3_path, np_array)
    id = id + total_num
    file3_path = os.path.join(output_dir1, f"{id}.npy")
    np.save(file3_path, np_array)
    id = id + total_num
    file3_path = os.path.join(output_dir1, f"{id}.npy")
    np.save(file3_path, np_array)




[[2]
 [1]
 [2]
 [1]]
[[2]
 [1]
 [1]
 [1]]
[[2]
 [1]
 [1]
 [2]]
[[2]
 [1]
 [2]
 [2]]
[[2]
 [3]
 [1]
 [2]]
[[2]
 [3]
 [1]
 [1]]
[[2]
 [3]
 [2]
 [1]]
[[2]
 [3]
 [2]
 [2]]
[[2]
 [2]
 [2]
 [2]]
[[2]
 [2]
 [2]
 [1]]
[[2]
 [2]
 [1]
 [1]]
[[2]
 [2]
 [1]
 [2]]
[[2]
 [0]
 [1]
 [0]]
[[2]
 [0]
 [2]
 [0]]
[[3]
 [1]
 [2]
 [2]]
[[4]
 [1]
 [2]
 [2]]
[[4]
 [1]
 [1]
 [2]]
[[4]
 [1]
 [1]
 [1]]
[[3]
 [1]
 [1]
 [1]]
[[3]
 [2]
 [1]
 [1]]
[[4]
 [2]
 [1]
 [1]]
[[4]
 [2]
 [1]
 [2]]
[[3]
 [2]
 [1]
 [2]]
[[3]
 [3]
 [1]
 [2]]
[[4]
 [3]
 [1]
 [2]]
[[3]
 [1]
 [1]
 [2]]
[[3]
 [1]
 [2]
 [1]]
[[3]
 [2]
 [2]
 [1]]
[[3]
 [2]
 [2]
 [2]]
[[3]
 [3]
 [2]
 [2]]
[[3]
 [3]
 [2]
 [1]]
[[3]
 [3]
 [1]
 [1]]
[[4]
 [1]
 [2]
 [1]]
[[4]
 [2]
 [2]
 [1]]
[[4]
 [2]
 [2]
 [2]]
[[4]
 [3]
 [2]
 [2]]
[[4]
 [3]
 [2]
 [1]]
[[4]
 [3]
 [1]
 [1]]


<>:5: SyntaxWarning: invalid escape sequence '\P'
<>:6: SyntaxWarning: invalid escape sequence '\P'
<>:5: SyntaxWarning: invalid escape sequence '\P'
<>:6: SyntaxWarning: invalid escape sequence '\P'
C:\Users\董子能\AppData\Local\Temp\ipykernel_3204\2017185279.py:5: SyntaxWarning: invalid escape sequence '\P'
  output_dir1 = "D:\Program\ThreeD\Project\easy\\train_dataset" # 保存数据路径
C:\Users\董子能\AppData\Local\Temp\ipykernel_3204\2017185279.py:6: SyntaxWarning: invalid escape sequence '\P'
  output_dir2 = "D:\Program\ThreeD\Project\easy\\test_dataset"
